# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zsjyh.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = MplCanvasWrapper(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 10, 471, 241))
        self.widget.setObjectName("widget")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 71, 16))
        self.label_7.setObjectName("label_7")
        self.TempGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.TempGroupBox.setGeometry(QtCore.QRect(520, 220, 271, 271))
        self.TempGroupBox.setObjectName("TempGroupBox")
        self.SetTempLineEdit = QtWidgets.QLineEdit(self.TempGroupBox)
        self.SetTempLineEdit.setGeometry(QtCore.QRect(70, 30, 61, 20))
        self.SetTempLineEdit.setText("")
        self.SetTempLineEdit.setObjectName("SetTempLineEdit")
        self.EnsureChangeTemp = QtWidgets.QPushButton(self.TempGroupBox)
        self.EnsureChangeTemp.setGeometry(QtCore.QRect(140, 30, 61, 21))
        self.EnsureChangeTemp.setObjectName("EnsureChangeTemp")
        self.label_4 = QtWidgets.QLabel(self.TempGroupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 30, 51, 16))
        self.label_4.setObjectName("label_4")
        self.DownTemp1 = QtWidgets.QPushButton(self.TempGroupBox)
        self.DownTemp1.setGeometry(QtCore.QRect(170, 70, 61, 31))
        self.DownTemp1.setObjectName("DownTemp1")
        self.UpTemp1 = QtWidgets.QPushButton(self.TempGroupBox)
        self.UpTemp1.setGeometry(QtCore.QRect(100, 70, 61, 31))
        self.UpTemp1.setObjectName("UpTemp1")
        self.label_5 = QtWidgets.QLabel(self.TempGroupBox)
        self.label_5.setGeometry(QtCore.QRect(0, 70, 91, 31))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.TempGroupBox)
        self.label_6.setGeometry(QtCore.QRect(0, 120, 81, 16))
        self.label_6.setObjectName("label_6")
        self.Stop_1 = QtWidgets.QPushButton(self.TempGroupBox)
        self.Stop_1.setGeometry(QtCore.QRect(170, 120, 61, 31))
        self.Stop_1.setObjectName("Stop_1")
        self.Launch1 = QtWidgets.QPushButton(self.TempGroupBox)
        self.Launch1.setGeometry(QtCore.QRect(100, 120, 61, 31))
        self.Launch1.setObjectName("Launch1")
        self.label_8 = QtWidgets.QLabel(self.TempGroupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 170, 91, 20))
        self.label_8.setObjectName("label_8")
        self.TempDisplay = QtWidgets.QLCDNumber(self.TempGroupBox)
        self.TempDisplay.setGeometry(QtCore.QRect(120, 170, 64, 23))
        self.TempDisplay.setSmallDecimalPoint(True)
        self.TempDisplay.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.TempDisplay.setProperty("value", 0.0)
        self.TempDisplay.setObjectName("TempDisplay")
        self.TempRequest = QtWidgets.QPushButton(self.TempGroupBox)
        self.TempRequest.setGeometry(QtCore.QRect(200, 170, 71, 21))
        self.TempRequest.setObjectName("TempRequest")
        self.StateLabel = QtWidgets.QLabel(self.TempGroupBox)
        self.StateLabel.setGeometry(QtCore.QRect(110, 200, 111, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StateLabel.sizePolicy().hasHeightForWidth())
        self.StateLabel.setSizePolicy(sizePolicy)
        self.StateLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.StateLabel.setObjectName("StateLabel")
        self.StateRequest = QtWidgets.QPushButton(self.TempGroupBox)
        self.StateRequest.setGeometry(QtCore.QRect(10, 210, 71, 21))
        self.StateRequest.setObjectName("StateRequest")
        self.SetDALineEdit = QtWidgets.QLineEdit(self.TempGroupBox)
        self.SetDALineEdit.setGeometry(QtCore.QRect(110, 240, 61, 20))
        self.SetDALineEdit.setText("")
        self.SetDALineEdit.setObjectName("SetDALineEdit")
        self.EnsureChangeDA = QtWidgets.QPushButton(self.TempGroupBox)
        self.EnsureChangeDA.setGeometry(QtCore.QRect(190, 240, 61, 21))
        self.EnsureChangeDA.setObjectName("EnsureChangeDA")
        self.label_15 = QtWidgets.QLabel(self.TempGroupBox)
        self.label_15.setGeometry(QtCore.QRect(10, 240, 91, 16))
        self.label_15.setObjectName("label_15")
        self.TimeGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.TimeGroupBox.setGeometry(QtCore.QRect(20, 260, 471, 191))
        self.TimeGroupBox.setObjectName("TimeGroupBox")
        self.timeLabel = QtWidgets.QLabel(self.TimeGroupBox)
        self.timeLabel.setGeometry(QtCore.QRect(10, 20, 200, 21))
        self.timeLabel.setMinimumSize(QtCore.QSize(150, 21))
        self.timeLabel.setMaximumSize(QtCore.QSize(200, 21))
        self.timeLabel.setObjectName("timeLabel")
        self.label = QtWidgets.QLabel(self.TimeGroupBox)
        self.label.setGeometry(QtCore.QRect(260, 20, 91, 20))
        self.label.setObjectName("label")
        self.DelayedLaunchlineEdit = QtWidgets.QLineEdit(self.TimeGroupBox)
        self.DelayedLaunchlineEdit.setEnabled(True)
        self.DelayedLaunchlineEdit.setGeometry(QtCore.QRect(80, 60, 81, 31))
        self.DelayedLaunchlineEdit.setText("")
        self.DelayedLaunchlineEdit.setObjectName("DelayedLaunchlineEdit")
        self.DelayedLaunch = QtWidgets.QPushButton(self.TimeGroupBox)
        self.DelayedLaunch.setGeometry(QtCore.QRect(190, 50, 81, 41))
        self.DelayedLaunch.setObjectName("DelayedLaunch")
        self.label_2 = QtWidgets.QLabel(self.TimeGroupBox)
        self.label_2.setGeometry(QtCore.QRect(0, 60, 61, 31))
        self.label_2.setObjectName("label_2")
        self.DelayedLaunchTimeRequest = QtWidgets.QPushButton(self.TimeGroupBox)
        self.DelayedLaunchTimeRequest.setGeometry(QtCore.QRect(300, 50, 101, 41))
        self.DelayedLaunchTimeRequest.setObjectName("DelayedLaunchTimeRequest")
        self.label_3 = QtWidgets.QLabel(self.TimeGroupBox)
        self.label_3.setGeometry(QtCore.QRect(0, 110, 51, 31))
        self.label_3.setObjectName("label_3")
        self.DelayedStop = QtWidgets.QPushButton(self.TimeGroupBox)
        self.DelayedStop.setGeometry(QtCore.QRect(190, 110, 81, 41))
        self.DelayedStop.setObjectName("DelayedStop")
        self.DelayedStopTimeRequest = QtWidgets.QPushButton(self.TimeGroupBox)
        self.DelayedStopTimeRequest.setGeometry(QtCore.QRect(300, 110, 101, 41))
        self.DelayedStopTimeRequest.setObjectName("DelayedStopTimeRequest")
        self.DelayedStoplineEdit = QtWidgets.QLineEdit(self.TimeGroupBox)
        self.DelayedStoplineEdit.setGeometry(QtCore.QRect(80, 110, 81, 31))
        self.DelayedStoplineEdit.setObjectName("DelayedStoplineEdit")
        self.DelayedTimeDisplay = QtWidgets.QLCDNumber(self.TimeGroupBox)
        self.DelayedTimeDisplay.setGeometry(QtCore.QRect(350, 20, 64, 23))
        self.DelayedTimeDisplay.setSmallDecimalPoint(True)
        self.DelayedTimeDisplay.setDigitCount(5)
        self.DelayedTimeDisplay.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.DelayedTimeDisplay.setProperty("value", 0.0)
        self.DelayedTimeDisplay.setObjectName("DelayedTimeDisplay")
        self.ComGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.ComGroupBox.setGeometry(QtCore.QRect(520, 10, 271, 201))
        self.ComGroupBox.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.ComGroupBox.setObjectName("ComGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.ComGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.serialDataBitComboBox = QtWidgets.QComboBox(self.ComGroupBox)
        self.serialDataBitComboBox.setObjectName("serialDataBitComboBox")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.serialDataBitComboBox.addItem("")
        self.gridLayout.addWidget(self.serialDataBitComboBox, 2, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.ComGroupBox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.openSerialButton = QtWidgets.QPushButton(self.ComGroupBox)
        self.openSerialButton.setObjectName("openSerialButton")
        self.gridLayout.addWidget(self.openSerialButton, 5, 0, 1, 1)
        self.closeSerialButton = QtWidgets.QPushButton(self.ComGroupBox)
        self.closeSerialButton.setObjectName("closeSerialButton")
        self.gridLayout.addWidget(self.closeSerialButton, 5, 1, 1, 1)
        self.refreshSerialButton = QtWidgets.QPushButton(self.ComGroupBox)
        self.refreshSerialButton.setObjectName("refreshSerialButton")
        self.gridLayout.addWidget(self.refreshSerialButton, 5, 2, 1, 1)
        self.serialCOMComboBox = QtWidgets.QComboBox(self.ComGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.serialCOMComboBox.sizePolicy().hasHeightForWidth())
        self.serialCOMComboBox.setSizePolicy(sizePolicy)
        self.serialCOMComboBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.serialCOMComboBox.setEditable(False)
        self.serialCOMComboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.serialCOMComboBox.setMinimumContentsLength(0)
        self.serialCOMComboBox.setObjectName("serialCOMComboBox")
        self.gridLayout.addWidget(self.serialCOMComboBox, 0, 2, 1, 1)
        self.serialBaudRateComboBox = QtWidgets.QComboBox(self.ComGroupBox)
        self.serialBaudRateComboBox.setObjectName("serialBaudRateComboBox")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.serialBaudRateComboBox.addItem("")
        self.gridLayout.addWidget(self.serialBaudRateComboBox, 1, 2, 1, 1)
        self.serialStopBitComboBox = QtWidgets.QComboBox(self.ComGroupBox)
        self.serialStopBitComboBox.setObjectName("serialStopBitComboBox")
        self.serialStopBitComboBox.addItem("")
        self.serialStopBitComboBox.addItem("")
        self.serialStopBitComboBox.addItem("")
        self.gridLayout.addWidget(self.serialStopBitComboBox, 4, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.ComGroupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.ComGroupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.ComGroupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.ComGroupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.serialParityComboBox = QtWidgets.QComboBox(self.ComGroupBox)
        self.serialParityComboBox.setObjectName("serialParityComboBox")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.serialParityComboBox.addItem("")
        self.gridLayout.addWidget(self.serialParityComboBox, 3, 2, 1, 1)
        self.debugLabel = QtWidgets.QLabel(self.centralwidget)
        self.debugLabel.setGeometry(QtCore.QRect(104, 470, 405, 29))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.debugLabel.sizePolicy().hasHeightForWidth())
        self.debugLabel.setSizePolicy(sizePolicy)
        self.debugLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.debugLabel.setObjectName("debugLabel")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(20, 470, 80, 29))
        self.label_14.setMaximumSize(QtCore.QSize(80, 30))
        self.label_14.setObjectName("label_14")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "实时温度曲线"))
        self.TempGroupBox.setTitle(_translate("MainWindow", "温度设置"))
        self.EnsureChangeTemp.setText(_translate("MainWindow", "确定"))
        self.label_4.setText(_translate("MainWindow", "设置温度"))
        self.DownTemp1.setText(_translate("MainWindow", "下降"))
        self.UpTemp1.setText(_translate("MainWindow", "上升"))
        self.label_5.setText(_translate("MainWindow", "温度微调（1摄氏度）"))
        self.label_6.setText(_translate("MainWindow", "启动/停止 温度控制"))
        self.Stop_1.setText(_translate("MainWindow", "停止"))
        self.Launch1.setText(_translate("MainWindow", "开始"))
        self.label_8.setText(_translate("MainWindow", "当前温度显示（摄氏度）"))
        self.TempRequest.setText(_translate("MainWindow", "查询温度"))
        self.StateLabel.setText(_translate("MainWindow", "无"))
        self.StateRequest.setText(_translate("MainWindow", "查询状态"))
        self.EnsureChangeDA.setText(_translate("MainWindow", "确定"))
        self.label_15.setText(_translate("MainWindow", "数模数据设置"))
        self.TimeGroupBox.setTitle(_translate("MainWindow", "时间设置"))
        self.timeLabel.setText(_translate("MainWindow", "time:"))
        self.label.setText(_translate("MainWindow", "延时时间显示(s)"))
        self.DelayedLaunch.setText(_translate("MainWindow", "延时启动"))
        self.label_2.setText(_translate("MainWindow", "启动时延"))
        self.DelayedLaunchTimeRequest.setText(_translate("MainWindow", "延时启动时间查询"))
        self.label_3.setText(_translate("MainWindow", "停止时延"))
        self.DelayedStop.setText(_translate("MainWindow", "延时停止"))
        self.DelayedStopTimeRequest.setText(_translate("MainWindow", "延时停止时间查询"))
        self.ComGroupBox.setTitle(_translate("MainWindow", "串口配置"))
        self.serialDataBitComboBox.setItemText(0, _translate("MainWindow", "5"))
        self.serialDataBitComboBox.setItemText(1, _translate("MainWindow", "6"))
        self.serialDataBitComboBox.setItemText(2, _translate("MainWindow", "7"))
        self.serialDataBitComboBox.setItemText(3, _translate("MainWindow", "8"))
        self.label_11.setText(_translate("MainWindow", "停止位"))
        self.openSerialButton.setText(_translate("MainWindow", "打开串口"))
        self.closeSerialButton.setText(_translate("MainWindow", "关闭串口"))
        self.refreshSerialButton.setText(_translate("MainWindow", "刷新串口"))
        self.serialBaudRateComboBox.setItemText(0, _translate("MainWindow", "2400"))
        self.serialBaudRateComboBox.setItemText(1, _translate("MainWindow", "4800"))
        self.serialBaudRateComboBox.setItemText(2, _translate("MainWindow", "9600"))
        self.serialBaudRateComboBox.setItemText(3, _translate("MainWindow", "115200"))
        self.serialBaudRateComboBox.setItemText(4, _translate("MainWindow", "460800"))
        self.serialStopBitComboBox.setItemText(0, _translate("MainWindow", "1"))
        self.serialStopBitComboBox.setItemText(1, _translate("MainWindow", "1.5"))
        self.serialStopBitComboBox.setItemText(2, _translate("MainWindow", "2"))
        self.label_13.setText(_translate("MainWindow", "数据位"))
        self.label_9.setText(_translate("MainWindow", "端口选择"))
        self.label_10.setText(_translate("MainWindow", "波特率"))
        self.label_12.setText(_translate("MainWindow", "奇偶校验位"))
        self.serialParityComboBox.setItemText(0, _translate("MainWindow", "NONE"))
        self.serialParityComboBox.setItemText(1, _translate("MainWindow", "EVEN"))
        self.serialParityComboBox.setItemText(2, _translate("MainWindow", "ODD"))
        self.serialParityComboBox.setItemText(3, _translate("MainWindow", "MARK"))
        self.serialParityComboBox.setItemText(4, _translate("MainWindow", "SPACE"))
        self.debugLabel.setText(_translate("MainWindow", "无"))
        self.label_14.setText(_translate("MainWindow", "运行状态显示："))

from mplCanvasWrapper import MplCanvasWrapper
